### ISSUE TITLE
some city geo can't plus together, raise ValueError

### ISSUE THREAD

**Issue by ailen9466** [cnmetlab/cnmaps#85]
get_adm_maps(city='长春市', level='市', only_polygon=True, record='first') + get_adm_maps(city='吉林市', level='市', only_polygon=True, record='first')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/jcma/.conda/envs/citynetwork/lib/python3.9/site-packages/cnmaps/maps.py", line 43, in __add__
    return self.union(other)
  File "/Users/jcma/.conda/envs/citynetwork/lib/python3.9/site-packages/cnmaps/maps.py", line 78, in union
    return self.drop_inner_duplicate(MapPolygon(union_result))
  File "/Users/jcma/.conda/envs/citynetwork/lib/python3.9/site-packages/cnmaps/maps.py", line 69, in drop_inner_duplicate
    polygons.remove(other)
ValueError: list.remove(x): x not in list

**Comment by ailen9466** [comment]
get_adm_maps(city='四平市', level='市', only_polygon=True, record='first') + get_adm_maps(city='长春市', level='市', only_polygon=True, record='first')
<cnmaps.maps.MapPolygon object at 0x17ef11b80>

看起来可能是吉林的问题，我用四平+吉林也汇报同样的错，四平+长春就可以。

**Comment by ailen9466** [comment]
get_adm_maps(city='吉林市', level='市', only_polygon=True, record='first') + get_adm_maps(city='辽源市', level='市', only_polygon=True, record='first')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/jcma/.conda/envs/citynetwork/lib/python3.9/site-packages/cnmaps/maps.py", line 43, in __add__
    return self.union(other)
  File "/Users/jcma/.conda/envs/citynetwork/lib/python3.9/site-packages/cnmaps/maps.py", line 78, in union
    return self.drop_inner_duplicate(MapPolygon(union_result))
  File "/Users/jcma/.conda/envs/citynetwork/lib/python3.9/site-packages/cnmaps/maps.py", line 69, in drop_inner_duplicate
    polygons.remove(other)
ValueError: list.remove(x): x not in list

吉林市可能数据源有问题，但是我不知道这个应该怎么找问题了。

**Comment by ailen9466** [comment]
修改maps.py的69行为：
                try:
                    polygons.remove(other)
                except:
                    continue
可以解决问题，估计还是边界的数据有问题。
代码洁癖不知道是否可以接受try的结构。
或者可以改为if之类的结构。

**Comment by Clarmy** [comment]
@ailen9466 已经在 1.1.1 版本中修复了这个问题
